{{- if .Values.system.enabled }}
apiVersion: edge.dacs.io/v1alpha1
kind: ChillSystem
metadata:
  name: {{ include "chill.systemName" . }}
  labels:
    {{- include "chill.labels" . | nindent 4 }}
spec:
  managementNamespace: {{ .Release.Namespace | quote }}
  nodeDiscovery:
    enabled: {{ .Values.nodeDiscovery.enabled }}
    daemonSetName: {{ printf "%s-node-discovery" (include "chill.fullname" .) | quote }}
    configMapName: {{ include "chill.nodeDiscoveryConfigName" . | quote }}
    configMapKey: config.yaml
  deviceDiscovery:
    enabled: {{ .Values.discovery.enabled }}
    labelKey: {{ .Values.discovery.labelKey | quote }}
    overwriteManualLabels: {{ .Values.discovery.overwriteManualLabels }}
    nodeLabelSelector: {{ include "chill.discoveryNodeLabelSelector" . | quote }}
    requireCatalogMatch: {{ .Values.discovery.requireCatalogMatch }}
    catalog:
      namespace: {{ .Release.Namespace | quote }}
      name: {{ include "chill.discoveryCatalogName" . | quote }}
      key: {{ include "chill.discoveryCatalogKey" . | quote }}
{{- end }}
