apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chill.operatorName" . }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "chill.labels" . | nindent 4 }}
rules:
{{ include "chill.operatorRoleRules" . | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chill.operatorName" . }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "chill.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chill.operatorName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "chill.operatorServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chill.operatorName" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "chill.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chill.operatorName" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "chill.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "chill.operatorName" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "chill.operatorServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
