{{- if .Values.nodeDiscovery.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chill.fullname" . }}-node-discovery
  labels:
    app.kubernetes.io/component: node-discovery
    {{- include "chill.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chill.fullname" . }}-node-discovery
  labels:
    app.kubernetes.io/component: node-discovery
    {{- include "chill.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chill.fullname" . }}-node-discovery
subjects:
  - kind: ServiceAccount
    name: {{ include "chill.nodeDiscoveryServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
