{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chill.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chill.labels" . | nindent 4 }}
{{- end }}
{{- if and .Values.nodeDiscovery.enabled .Values.nodeDiscovery.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chill.nodeDiscoveryServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: node-discovery
    {{- include "chill.labels" . | nindent 4 }}
{{- end }}
