apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chilloperator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "chilloperator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      {{- include "chilloperator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: operator
      labels:
        app.kubernetes.io/component: operator
        {{- include "chilloperator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "chilloperator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: operator
          image: "{{ include "chilloperator.image" . }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          command:
            - /operator
          args:
            - --metrics-bind-address={{ .Values.operator.metricsBindAddress }}
            - --health-probe-bind-address={{ .Values.operator.healthProbeBindAddress }}
            - --system-status-name={{ .Values.system.name }}
            - --system-status-namespace={{ .Release.Namespace }}
            - --system-status-operator-deployment-name={{ include "chilloperator.fullname" . }}
            - --system-status-refresh-interval={{ .Values.system.refreshInterval }}
            {{- if .Values.operator.leaderElection }}
            - --leader-elect
            {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10
