resources:
- bases/edge.dacs.io_chillsystems.yaml
- bases/edge.dacs.io_deviceclasses.yaml
- bases/edge.dacs.io_modelspecs.yaml
- bases/edge.dacs.io_deviceprofiles.yaml
- bases/edge.dacs.io_clusterenergymodels.yaml
# +kubebuilder:scaffold:crdkustomizeresource
